### ISSUE TITLE
README 里面， B3/S23 吧？

### ISSUE THREAD

**Issue by calcuboy** [zhou-tian-xing/Conway-life-game#1]
README 里面， B3/S23 吧？

**Comment by zhou-tian-xing** [comment]
是，当时写错了...
没想到随手发的项目还有人写issue
----- 原始邮件 -----
发件人：calcuboy ***@***.***>
收件人：zhou-tian-xing/Conway-life-game ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[zhou-tian-xing/Conway-life-game]_README_里面，_B3/S23_吧？_(Issue_#1)
日期：2024年06月16日 15点50分


README 里面， B3/S23 吧？
